import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Preloader from "../components/Preloader";

import { TRPCReactProvider } from "@/trpc/react";
import TopNavBar from "./_components/TopNavBar";

export const metadata: Metadata = {
  title: "Code By Vince",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TopNavBar />
        <Preloader />
        <TRPCReactProvider>
          <main className="pt-[96px]">{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
